/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnnouncementRouteImport } from './routes/announcement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceSearchRouteImport } from './routes/space.search'
import { Route as SpaceIdRouteImport } from './routes/space.$id'
import { Route as SignupBrandProfileRouteImport } from './routes/signup.brand-profile'
import { Route as MypageWithdrawRouteImport } from './routes/mypage.withdraw'
import { Route as MypageProfileRouteImport } from './routes/mypage.profile'
import { Route as MypageMessagesRouteImport } from './routes/mypage.messages'
import { Route as MypageLikedRouteImport } from './routes/mypage.liked'
import { Route as MypageBrandProfileRouteImport } from './routes/mypage.brand-profile'
import { Route as AnnouncementSearchRouteImport } from './routes/announcement.search'
import { Route as AnnouncementIdRouteImport } from './routes/announcement.$id'

const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRoute = AnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSearchRoute = SpaceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceIdRoute = SpaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpaceRoute,
} as any)
const SignupBrandProfileRoute = SignupBrandProfileRouteImport.update({
  id: '/brand-profile',
  path: '/brand-profile',
  getParentRoute: () => SignupRoute,
} as any)
const MypageWithdrawRoute = MypageWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => MypageRoute,
} as any)
const MypageProfileRoute = MypageProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MypageRoute,
} as any)
const MypageMessagesRoute = MypageMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MypageRoute,
} as any)
const MypageLikedRoute = MypageLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => MypageRoute,
} as any)
const MypageBrandProfileRoute = MypageBrandProfileRouteImport.update({
  id: '/brand-profile',
  path: '/brand-profile',
  getParentRoute: () => MypageRoute,
} as any)
const AnnouncementSearchRoute = AnnouncementSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AnnouncementRoute,
} as any)
const AnnouncementIdRoute = AnnouncementIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRouteWithChildren
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRouteWithChildren
  '/space': typeof SpaceRouteWithChildren
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/liked': typeof MypageLikedRoute
  '/mypage/messages': typeof MypageMessagesRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRoute
  '/space/search': typeof SpaceSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRouteWithChildren
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRouteWithChildren
  '/space': typeof SpaceRouteWithChildren
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/liked': typeof MypageLikedRoute
  '/mypage/messages': typeof MypageMessagesRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRoute
  '/space/search': typeof SpaceSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRouteWithChildren
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRouteWithChildren
  '/space': typeof SpaceRouteWithChildren
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/liked': typeof MypageLikedRoute
  '/mypage/messages': typeof MypageMessagesRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRoute
  '/space/search': typeof SpaceSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcement'
    | '/login'
    | '/mypage'
    | '/reservation'
    | '/signup'
    | '/space'
    | '/announcement/$id'
    | '/announcement/search'
    | '/mypage/brand-profile'
    | '/mypage/liked'
    | '/mypage/messages'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement'
    | '/login'
    | '/mypage'
    | '/reservation'
    | '/signup'
    | '/space'
    | '/announcement/$id'
    | '/announcement/search'
    | '/mypage/brand-profile'
    | '/mypage/liked'
    | '/mypage/messages'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/login'
    | '/mypage'
    | '/reservation'
    | '/signup'
    | '/space'
    | '/announcement/$id'
    | '/announcement/search'
    | '/mypage/brand-profile'
    | '/mypage/liked'
    | '/mypage/messages'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRoute: typeof AnnouncementRouteWithChildren
  LoginRoute: typeof LoginRoute
  MypageRoute: typeof MypageRouteWithChildren
  ReservationRoute: typeof ReservationRoute
  SignupRoute: typeof SignupRouteWithChildren
  SpaceRoute: typeof SpaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/search': {
      id: '/space/search'
      path: '/search'
      fullPath: '/space/search'
      preLoaderRoute: typeof SpaceSearchRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/space/$id': {
      id: '/space/$id'
      path: '/$id'
      fullPath: '/space/$id'
      preLoaderRoute: typeof SpaceIdRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/signup/brand-profile': {
      id: '/signup/brand-profile'
      path: '/brand-profile'
      fullPath: '/signup/brand-profile'
      preLoaderRoute: typeof SignupBrandProfileRouteImport
      parentRoute: typeof SignupRoute
    }
    '/mypage/withdraw': {
      id: '/mypage/withdraw'
      path: '/withdraw'
      fullPath: '/mypage/withdraw'
      preLoaderRoute: typeof MypageWithdrawRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/profile': {
      id: '/mypage/profile'
      path: '/profile'
      fullPath: '/mypage/profile'
      preLoaderRoute: typeof MypageProfileRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/messages': {
      id: '/mypage/messages'
      path: '/messages'
      fullPath: '/mypage/messages'
      preLoaderRoute: typeof MypageMessagesRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/liked': {
      id: '/mypage/liked'
      path: '/liked'
      fullPath: '/mypage/liked'
      preLoaderRoute: typeof MypageLikedRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/brand-profile': {
      id: '/mypage/brand-profile'
      path: '/brand-profile'
      fullPath: '/mypage/brand-profile'
      preLoaderRoute: typeof MypageBrandProfileRouteImport
      parentRoute: typeof MypageRoute
    }
    '/announcement/search': {
      id: '/announcement/search'
      path: '/search'
      fullPath: '/announcement/search'
      preLoaderRoute: typeof AnnouncementSearchRouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/announcement/$id': {
      id: '/announcement/$id'
      path: '/$id'
      fullPath: '/announcement/$id'
      preLoaderRoute: typeof AnnouncementIdRouteImport
      parentRoute: typeof AnnouncementRoute
    }
  }
}

interface AnnouncementRouteChildren {
  AnnouncementIdRoute: typeof AnnouncementIdRoute
  AnnouncementSearchRoute: typeof AnnouncementSearchRoute
}

const AnnouncementRouteChildren: AnnouncementRouteChildren = {
  AnnouncementIdRoute: AnnouncementIdRoute,
  AnnouncementSearchRoute: AnnouncementSearchRoute,
}

const AnnouncementRouteWithChildren = AnnouncementRoute._addFileChildren(
  AnnouncementRouteChildren,
)

interface MypageRouteChildren {
  MypageBrandProfileRoute: typeof MypageBrandProfileRoute
  MypageLikedRoute: typeof MypageLikedRoute
  MypageMessagesRoute: typeof MypageMessagesRoute
  MypageProfileRoute: typeof MypageProfileRoute
  MypageWithdrawRoute: typeof MypageWithdrawRoute
}

const MypageRouteChildren: MypageRouteChildren = {
  MypageBrandProfileRoute: MypageBrandProfileRoute,
  MypageLikedRoute: MypageLikedRoute,
  MypageMessagesRoute: MypageMessagesRoute,
  MypageProfileRoute: MypageProfileRoute,
  MypageWithdrawRoute: MypageWithdrawRoute,
}

const MypageRouteWithChildren =
  MypageRoute._addFileChildren(MypageRouteChildren)

interface SignupRouteChildren {
  SignupBrandProfileRoute: typeof SignupBrandProfileRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupBrandProfileRoute: SignupBrandProfileRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface SpaceRouteChildren {
  SpaceIdRoute: typeof SpaceIdRoute
  SpaceSearchRoute: typeof SpaceSearchRoute
}

const SpaceRouteChildren: SpaceRouteChildren = {
  SpaceIdRoute: SpaceIdRoute,
  SpaceSearchRoute: SpaceSearchRoute,
}

const SpaceRouteWithChildren = SpaceRoute._addFileChildren(SpaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRoute: AnnouncementRouteWithChildren,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRouteWithChildren,
  ReservationRoute: ReservationRoute,
  SignupRoute: SignupRouteWithChildren,
  SpaceRoute: SpaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
