/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceIndexRouteImport } from './routes/space/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as MypageIndexRouteImport } from './routes/mypage/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LikedIndexRouteImport } from './routes/liked/index'
import { Route as AnnouncementIndexRouteImport } from './routes/announcement/index'
import { Route as AlarmsIndexRouteImport } from './routes/alarms/index'
import { Route as SpaceSearchRouteImport } from './routes/space/search'
import { Route as SpaceIdRouteImport } from './routes/space/$id'
import { Route as SignupBrandProfileRouteImport } from './routes/signup/brand-profile'
import { Route as ReservationApplyRouteImport } from './routes/reservation/apply'
import { Route as MypageWithdrawRouteImport } from './routes/mypage/withdraw'
import { Route as MypageProfileRouteImport } from './routes/mypage/profile'
import { Route as MypageBrandProfileRouteImport } from './routes/mypage/brand-profile'
import { Route as MessagesRoomIdRouteImport } from './routes/messages/$roomId'
import { Route as AnnouncementSearchRouteImport } from './routes/announcement/search'
import { Route as AnnouncementIdRouteImport } from './routes/announcement/$id'
import { Route as SpaceIdMapRouteImport } from './routes/space/$id.map'
import { Route as ReservationApplyInfoRouteImport } from './routes/reservation/apply.info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIndexRoute = SpaceIndexRouteImport.update({
  id: '/space/',
  path: '/space/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedIndexRoute = LikedIndexRouteImport.update({
  id: '/liked/',
  path: '/liked/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementIndexRoute = AnnouncementIndexRouteImport.update({
  id: '/announcement/',
  path: '/announcement/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsIndexRoute = AlarmsIndexRouteImport.update({
  id: '/alarms/',
  path: '/alarms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSearchRoute = SpaceSearchRouteImport.update({
  id: '/space/search',
  path: '/space/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdRoute = SpaceIdRouteImport.update({
  id: '/space/$id',
  path: '/space/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupBrandProfileRoute = SignupBrandProfileRouteImport.update({
  id: '/signup/brand-profile',
  path: '/signup/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationApplyRoute = ReservationApplyRouteImport.update({
  id: '/reservation/apply',
  path: '/reservation/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageWithdrawRoute = MypageWithdrawRouteImport.update({
  id: '/mypage/withdraw',
  path: '/mypage/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageProfileRoute = MypageProfileRouteImport.update({
  id: '/mypage/profile',
  path: '/mypage/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageBrandProfileRoute = MypageBrandProfileRouteImport.update({
  id: '/mypage/brand-profile',
  path: '/mypage/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoomIdRoute = MessagesRoomIdRouteImport.update({
  id: '/messages/$roomId',
  path: '/messages/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementSearchRoute = AnnouncementSearchRouteImport.update({
  id: '/announcement/search',
  path: '/announcement/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementIdRoute = AnnouncementIdRouteImport.update({
  id: '/announcement/$id',
  path: '/announcement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdMapRoute = SpaceIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => SpaceIdRoute,
} as any)
const ReservationApplyInfoRoute = ReservationApplyInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ReservationApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/messages/$roomId': typeof MessagesRoomIdRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/reservation/apply': typeof ReservationApplyRouteWithChildren
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRouteWithChildren
  '/space/search': typeof SpaceSearchRoute
  '/alarms/': typeof AlarmsIndexRoute
  '/announcement/': typeof AnnouncementIndexRoute
  '/liked/': typeof LikedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/space/': typeof SpaceIndexRoute
  '/reservation/apply/info': typeof ReservationApplyInfoRoute
  '/space/$id/map': typeof SpaceIdMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/messages/$roomId': typeof MessagesRoomIdRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/reservation/apply': typeof ReservationApplyRouteWithChildren
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRouteWithChildren
  '/space/search': typeof SpaceSearchRoute
  '/alarms': typeof AlarmsIndexRoute
  '/announcement': typeof AnnouncementIndexRoute
  '/liked': typeof LikedIndexRoute
  '/login': typeof LoginIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/mypage': typeof MypageIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/signup': typeof SignupIndexRoute
  '/space': typeof SpaceIndexRoute
  '/reservation/apply/info': typeof ReservationApplyInfoRoute
  '/space/$id/map': typeof SpaceIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement/$id': typeof AnnouncementIdRoute
  '/announcement/search': typeof AnnouncementSearchRoute
  '/messages/$roomId': typeof MessagesRoomIdRoute
  '/mypage/brand-profile': typeof MypageBrandProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/withdraw': typeof MypageWithdrawRoute
  '/reservation/apply': typeof ReservationApplyRouteWithChildren
  '/signup/brand-profile': typeof SignupBrandProfileRoute
  '/space/$id': typeof SpaceIdRouteWithChildren
  '/space/search': typeof SpaceSearchRoute
  '/alarms/': typeof AlarmsIndexRoute
  '/announcement/': typeof AnnouncementIndexRoute
  '/liked/': typeof LikedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/space/': typeof SpaceIndexRoute
  '/reservation/apply/info': typeof ReservationApplyInfoRoute
  '/space/$id/map': typeof SpaceIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcement/$id'
    | '/announcement/search'
    | '/messages/$roomId'
    | '/mypage/brand-profile'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/reservation/apply'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
    | '/alarms/'
    | '/announcement/'
    | '/liked/'
    | '/login/'
    | '/messages/'
    | '/mypage/'
    | '/reservation/'
    | '/signup/'
    | '/space/'
    | '/reservation/apply/info'
    | '/space/$id/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement/$id'
    | '/announcement/search'
    | '/messages/$roomId'
    | '/mypage/brand-profile'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/reservation/apply'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
    | '/alarms'
    | '/announcement'
    | '/liked'
    | '/login'
    | '/messages'
    | '/mypage'
    | '/reservation'
    | '/signup'
    | '/space'
    | '/reservation/apply/info'
    | '/space/$id/map'
  id:
    | '__root__'
    | '/'
    | '/announcement/$id'
    | '/announcement/search'
    | '/messages/$roomId'
    | '/mypage/brand-profile'
    | '/mypage/profile'
    | '/mypage/withdraw'
    | '/reservation/apply'
    | '/signup/brand-profile'
    | '/space/$id'
    | '/space/search'
    | '/alarms/'
    | '/announcement/'
    | '/liked/'
    | '/login/'
    | '/messages/'
    | '/mypage/'
    | '/reservation/'
    | '/signup/'
    | '/space/'
    | '/reservation/apply/info'
    | '/space/$id/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementIdRoute: typeof AnnouncementIdRoute
  AnnouncementSearchRoute: typeof AnnouncementSearchRoute
  MessagesRoomIdRoute: typeof MessagesRoomIdRoute
  MypageBrandProfileRoute: typeof MypageBrandProfileRoute
  MypageProfileRoute: typeof MypageProfileRoute
  MypageWithdrawRoute: typeof MypageWithdrawRoute
  ReservationApplyRoute: typeof ReservationApplyRouteWithChildren
  SignupBrandProfileRoute: typeof SignupBrandProfileRoute
  SpaceIdRoute: typeof SpaceIdRouteWithChildren
  SpaceSearchRoute: typeof SpaceSearchRoute
  AlarmsIndexRoute: typeof AlarmsIndexRoute
  AnnouncementIndexRoute: typeof AnnouncementIndexRoute
  LikedIndexRoute: typeof LikedIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MypageIndexRoute: typeof MypageIndexRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  SpaceIndexRoute: typeof SpaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/': {
      id: '/space/'
      path: '/space'
      fullPath: '/space/'
      preLoaderRoute: typeof SpaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation/'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/': {
      id: '/mypage/'
      path: '/mypage'
      fullPath: '/mypage/'
      preLoaderRoute: typeof MypageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked/': {
      id: '/liked/'
      path: '/liked'
      fullPath: '/liked/'
      preLoaderRoute: typeof LikedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/': {
      id: '/announcement/'
      path: '/announcement'
      fullPath: '/announcement/'
      preLoaderRoute: typeof AnnouncementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms/': {
      id: '/alarms/'
      path: '/alarms'
      fullPath: '/alarms/'
      preLoaderRoute: typeof AlarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/search': {
      id: '/space/search'
      path: '/space/search'
      fullPath: '/space/search'
      preLoaderRoute: typeof SpaceSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$id': {
      id: '/space/$id'
      path: '/space/$id'
      fullPath: '/space/$id'
      preLoaderRoute: typeof SpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/brand-profile': {
      id: '/signup/brand-profile'
      path: '/signup/brand-profile'
      fullPath: '/signup/brand-profile'
      preLoaderRoute: typeof SignupBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/apply': {
      id: '/reservation/apply'
      path: '/reservation/apply'
      fullPath: '/reservation/apply'
      preLoaderRoute: typeof ReservationApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/withdraw': {
      id: '/mypage/withdraw'
      path: '/mypage/withdraw'
      fullPath: '/mypage/withdraw'
      preLoaderRoute: typeof MypageWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/profile': {
      id: '/mypage/profile'
      path: '/mypage/profile'
      fullPath: '/mypage/profile'
      preLoaderRoute: typeof MypageProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/brand-profile': {
      id: '/mypage/brand-profile'
      path: '/mypage/brand-profile'
      fullPath: '/mypage/brand-profile'
      preLoaderRoute: typeof MypageBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$roomId': {
      id: '/messages/$roomId'
      path: '/messages/$roomId'
      fullPath: '/messages/$roomId'
      preLoaderRoute: typeof MessagesRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/search': {
      id: '/announcement/search'
      path: '/announcement/search'
      fullPath: '/announcement/search'
      preLoaderRoute: typeof AnnouncementSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/$id': {
      id: '/announcement/$id'
      path: '/announcement/$id'
      fullPath: '/announcement/$id'
      preLoaderRoute: typeof AnnouncementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$id/map': {
      id: '/space/$id/map'
      path: '/map'
      fullPath: '/space/$id/map'
      preLoaderRoute: typeof SpaceIdMapRouteImport
      parentRoute: typeof SpaceIdRoute
    }
    '/reservation/apply/info': {
      id: '/reservation/apply/info'
      path: '/info'
      fullPath: '/reservation/apply/info'
      preLoaderRoute: typeof ReservationApplyInfoRouteImport
      parentRoute: typeof ReservationApplyRoute
    }
  }
}

interface ReservationApplyRouteChildren {
  ReservationApplyInfoRoute: typeof ReservationApplyInfoRoute
}

const ReservationApplyRouteChildren: ReservationApplyRouteChildren = {
  ReservationApplyInfoRoute: ReservationApplyInfoRoute,
}

const ReservationApplyRouteWithChildren =
  ReservationApplyRoute._addFileChildren(ReservationApplyRouteChildren)

interface SpaceIdRouteChildren {
  SpaceIdMapRoute: typeof SpaceIdMapRoute
}

const SpaceIdRouteChildren: SpaceIdRouteChildren = {
  SpaceIdMapRoute: SpaceIdMapRoute,
}

const SpaceIdRouteWithChildren =
  SpaceIdRoute._addFileChildren(SpaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementIdRoute: AnnouncementIdRoute,
  AnnouncementSearchRoute: AnnouncementSearchRoute,
  MessagesRoomIdRoute: MessagesRoomIdRoute,
  MypageBrandProfileRoute: MypageBrandProfileRoute,
  MypageProfileRoute: MypageProfileRoute,
  MypageWithdrawRoute: MypageWithdrawRoute,
  ReservationApplyRoute: ReservationApplyRouteWithChildren,
  SignupBrandProfileRoute: SignupBrandProfileRoute,
  SpaceIdRoute: SpaceIdRouteWithChildren,
  SpaceSearchRoute: SpaceSearchRoute,
  AlarmsIndexRoute: AlarmsIndexRoute,
  AnnouncementIndexRoute: AnnouncementIndexRoute,
  LikedIndexRoute: LikedIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MypageIndexRoute: MypageIndexRoute,
  ReservationIndexRoute: ReservationIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  SpaceIndexRoute: SpaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
